apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-2
  namespace: my-ns
  labels:
    app: app-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-2
  template:
    metadata:
      labels:
        app: app-2
    spec:
      nodeSelector:
        label2: "True"
      containers:
      - name: app-2
        image: busybox
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: mypvc
      volumes:
      - name: mypvc
        persistentVolumeClaim:
          claimName: my-pvc