apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-2
  namespace: my-ns
  labels:
    app: app-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-1
  template:
    metadata:
      labels:
        app: app-1
    spec:
      nodeSelector:
        label1: "True"
      containers:
      - name: app-1
        image: busybox
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: mypvc
      volumes:
      - name: mypvc
        persistentVolumeClaim:
          claimName: my-pvc