apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-deployment-2
  namespace: my-ns
  labels:
    app: nginx-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-2
  template:
    metadata:
      labels:
        app: nginx-2
    spec:
      nodeSelector:
        label2: "True"
      containers:
      - name: nginx-2
        image: nginx
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: mypvc
      volumes:
      - name: mypvc
        persistentVolumeClaim:
          claimName: my-pvc