kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-pvc
  namespace: my-ns
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: standard-rwx
  resources:
    requests:
      storage: 1Ti